### ISSUE TITLE
Cutscenka z dialogami - pt. 1

### ISSUE THREAD

**Issue by Spookyless** [Truly-Depressed-Developers/steelworks#18]
Implementujemy cutscenki, narazie jedna po drugiej, ze wszystkimi dialogami i efektami tekstów.
Teksty nie będą na finalnych pozycjach, ze względu na brak grafik.

**Comment by Spookyless** [comment]
Blocked by #19 #35

**Comment by rubikon02** [comment]
Już nie blocked

**Comment by Spookyless** [comment]
Priorytety sprawiły, że zadanie trzeba było odsunąć - kontynuowane w #89
