### ISSUE TITLE
Podpięcie stamina bar

### ISSUE THREAD

**Issue by rubikon02** [Truly-Depressed-Developers/steelworks#32]
Do uników i wypędzania - gracz musi znaleźć balans pomiędzy defensywą i ofensywą

**Comment by Spookyless** [comment]
Co z normalnymi atakami? Też będą kosztować staminę?

**Comment by rubikon02** [comment]
Nie. Gracz będzie mógł w ryzykownej sytuacji dobić ducha, ale bardziej będzie mu się opłacało efektywnie unikać pocisków, żeby mieć staminę, żeby uwolnić ducha, a to jest dla niego lepsze, bo TBD
