### ISSUE TITLE
Camera movement

### ISSUE THREAD

**Issue by Spookyless** [Truly-Depressed-Developers/steelworks#38]
- [x] Kamera podąża za graczem
- [x] W momencie otrzymania obrażeń lekki shake [?]
- [ ] Podczas wyzwalania przeciwników zbliżenie na gracza + przeciwnika

**Comment by Spookyless** [comment]
Zdecydowanie korzystamy z Cinemachine

**Comment by MBrosik** [comment]
@Spookyless 
O co chodzi w tym punkcie?
```Podczas wyzwalania przeciwników zbliżenie na gracza + przeciwnika```
Że jak enemy pojawi się na scenie to camera ustawia się pośrodku gracza i przeciwników?

**Comment by Spookyless** [comment]
Nie - gdy gracz wykonuje na przeciwniku atak wyzwalający (podniesienie krzyża) kamera powinna się na nich zbliżyć - w momencie przerwania lub sukcesu wraca do poprzedniego stanu

**Comment by MBrosik** [comment]
Ok, dzięki
