### ISSUE TITLE
Atak gracza bije wielokrotnie

### ISSUE THREAD

**Issue by Spookyless** [Truly-Depressed-Developers/steelworks#49]
Jeśli podczas ataku przeciwnik będzie w triggerze, wyjdzie z niego i wejdzie ponownie, to otrzyma podwójne obrażenia z tego samego ataku
Pytanie - trzeba to rozwiązywać, czy wykorzystujemy [Ostrich algorithm](https://en.wikipedia.org/wiki/Ostrich_algorithm)?

**Comment by rubikon02** [comment]
Aktualnie włącza się collider (co może zadać obrażenia), a potem się przesuwa co może nałożyć obrażenia jeszcze raz. Ostatecznie zamiast ruchomej broni będzie animacja z aseprite. Może trigger będzie włączał się na chwilę i wyłączał?

**Comment by Spookyless** [comment]
Czekamy na animację ataku

**Comment by Spookyless** [comment]
Nie mamy na to czasu
