### ISSUE TITLE
Bug specjalnego ataku 

### ISSUE THREAD

**Issue by rubikon02** [Truly-Depressed-Developers/steelworks#51]
Użycie specjalnego ataku v nie zatrzymuje gracza jeżeli nie trafi on żadnego wroga. W efekcie gracz może kliknąć v, podejść do wroga aby w ostatnim momencie działania v go dotknąć i v się kończy pokonując go. Gracz jest wtedy bardzo krótko blisko wroga i mniej się naraża

**Comment by Spookyless** [comment]
Użycie specjalnego ataku nie zatrzymuje również wroga - wprowadzone w #47, została usunięta logika sprawdzająca, czy przeciwnik może się ruszyć

**Comment by Spookyless** [comment]
Wygląda również na to, że gracz przy otrzymaniu obrażeń nie przerywa ataku

**Comment by Spookyless** [comment]
Z #58
> Enemy w trakcie animacji śmierci nadal może wystrzelić buleta który zadaje graczowi obrażenia, pomimo to, że ten enemy już tak naprawdę nie żyje
