### ISSUE TITLE
Enemy bije w trakcie śmierci

### ISSUE THREAD

**Issue by MSiorr** [Truly-Depressed-Developers/steelworks#58]
Enemy w trakcie animacji śmierci nadal może wystrzelić buleta który zadaje graczowi obrażenia, pomimo to, że ten enemy już tak naprawdę nie żyje

**Comment by Spookyless** [comment]
Bug z #47 - został usunięty fragment kodu sprawdzający, czy enemy jest zafreezowany

**Comment by Spookyless** [comment]
Zostanie rozwiązane w #51
