### ISSUE TITLE
Powrót zooma kamery

### ISSUE THREAD

**Issue by MSiorr** [Truly-Depressed-Developers/steelworks#59]
Czasami po zabiciu 2 enemy na scenie zoom kamery nie wraca na pozycję początkową i biegamy cały czas ze zwiększonym zoomem

**Comment by Spookyless** [comment]
"Zabicie" masz na myśli wyzwolenie?

**Comment by Twarug** [comment]
Na wyzwolenie

**Comment by Spookyless** [comment]
Błąd pojawia się przy spamieniu specjalnym atakiem - nie mamy staminy, aby go wykonać, ale kamera się przybliża.. i nie ma limitu, jak bardzo
![image](https://github.com/Truly-Depressed-Developers/steelworks/assets/42909064/c0872a2f-48cd-44a2-98cc-d6f52caa8828)

**Comment by Spookyless** [comment]
Okazuje się że błąd naprawiłem już wcześniej, ale cofnąłem tego commita

**Comment by Twarug** [comment]
mogę to zrobić przy okazji tych bugów tego ataku

**Comment by Spookyless** [comment]
Mam już fixa
