### ISSUE TITLE
Przyciemnienie podczas gry

### ISSUE THREAD

**Issue by MSiorr** [Truly-Depressed-Developers/steelworks#97]
Dodanie przyciemnienia i wokol gracza jest zrodlo swiatla, dzieki czemu ciekawy efekt i klimat.

Jesli gracz zawsze na srodku mapy, to mozna zostosowac efekt Vignette, czyli ze na kamerze gradient przyciemniajcy przy krawedzich ekranu

**Comment by MBrosik** [comment]
@Spookyless jak będzie walka z bosem to zrobię to:
```Dodanie przyciemnienia i wokol gracza jest zrodlo swiatla, dzieki czemu ciekawy efekt i klimat. ```

Na razie jest tylko to:
```Jesli gracz zawsze na srodku mapy, to mozna zostosowac efekt Vignette, czyli ze na kamerze gradient przyciemniajcy przy krawedzich ekranu```

**Comment by Spookyless** [comment]
oke
