### ISSUE TITLE
Tytuł gry

### ISSUE THREAD

**Issue by rubikon02** [Truly-Depressed-Developers/steelworks#98]

**Comment by MBrosik** [comment]
Dziady: Klątwa guślarza

**Comment by rubikon02** [comment]
Pandemonium - sytuacja, miejsce lub wydarzenie, które jest przerażające i chaotyczne

**Comment by MBrosik** [comment]
Pandemonium - mroczne widmo
Pandemonium - powrót guślarza
Pandemonium - zemsta guślarza
Pandemonium - ostatni guślarz

**Comment by Spookyless** [comment]
Pandemonium
